import './style.css';
import QRCode from 'qrcode';
import { initialData } from './data.js';

const key='foodlink-prototipo-v1';
let db;
try { const saved=JSON.parse(localStorage.getItem(key)); db=saved?.restaurants?.length&&Array.isArray(saved.products)&&Array.isArray(saved.favorites)?saved:structuredClone(initialData); } catch { db=structuredClone(initialData); }
let search='',category='Todos',map=false,adminSection='cardapio',toastTimer;
const app=document.querySelector('#app'), modal=document.querySelector('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inlineAssets=markup=>markup.replace(/src="(\/assets\/[^"]+)"/g,(match,path)=>window.FOODLINK_ASSETS?.[path]?`src="${window.FOODLINK_ASSETS[path]}"`:match);
const price=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
const iconPaths={search:'<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 4.5 4.5"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',back:'<path d="M20 12H5m6-6-6 6 6 6"/>',heart:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 5.9l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>',qr:'<path d="M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h3v3h3v3h-6zM12 3v6M3 12h6M12 12h9M12 15v6"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',store:'<path d="M3 10 5 3h14l2 7M3 10h18M5 10v11h14V10M9 21v-7h6v7"/>',plus:'<path d="M12 5v14M5 12h14"/>',edit:'<path d="m15 5 4 4M4 20l5-1L21 7l-4-4L5 15z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L20 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',food:'<path d="M5 3v6c0 4 6 4 6 0V3M8 3v18M19 3c-4 3-5 8 0 9v9M19 3v9"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="8" cy="18" r="2"/>',palette:'<path d="M12 3a9 9 0 1 0 0 18h2a2 2 0 0 0 0-4h-1a2 2 0 0 1 0-4h3a5 5 0 0 0 0-10Z"/><path d="M7 8h.01M11 6h.01M6 13h.01"/>',list:'<path d="M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1"/>'};
const ic=(n,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[n]||iconPaths.food}</svg>`;
const logo=()=>`<a href="#/" class="brand" aria-label="FoodLink, início"><svg viewBox="0 0 30 38" fill="none" aria-hidden="true"><path d="M15 36S2 22 2 14A13 13 0 1 1 28 14c0 8-13 22-13 22Z" fill="#D9643A"/><path d="M10 7v10c0 5 10 5 10 0V7M15 7v26" stroke="#FAF7F2" stroke-width="2.4" stroke-linecap="round"/></svg><span>Food<b>Link</b></span></a>`;
const save=()=>{try{localStorage.setItem(key,JSON.stringify(db));return true;}catch{toast('Não foi possível salvar. Tente uma imagem menor.');return false;}};
const toast=text=>{const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500);};
const route=()=>location.hash.slice(1)||'/';
const current=()=>db.restaurants.find(r=>r.id===db.selected)||db.restaurants[0];
const go=path=>{if(route()===path)render();else location.hash=path;};
const favorite=id=>db.favorites.includes(id);
const heart=r=>`<button class="icon-btn favorite ${favorite(r.id)?'active':''}" data-action="favorite" data-id="${r.id}" aria-label="${favorite(r.id)?'Remover':'Adicionar'} ${esc(r.name)} ${favorite(r.id)?'dos':'aos'} favoritos" aria-pressed="${favorite(r.id)}">${ic('heart')}</button>`;
const foot=()=>`<footer class="footer">${logo()}<span>Restaurantes conectados com você</span><small>Protótipo acadêmico · locais e preços de demonstração</small></footer>`;
function header(active=''){return `<header class="topbar">${logo()}<nav aria-label="Navegação principal"><a class="${active==='explorar'?'selected':''}" href="#/explorar">Explorar</a><a class="${active==='favoritos'?'selected':''}" href="#/favoritos">Favoritos ${db.favorites.length?`<span class="count">${db.favorites.length}</span>`:''}</a><a class="${active==='qr'?'selected':''}" href="#/escanear">${ic('qr')}<span>Ler QR Code</span></a></nav><a class="btn outline small" href="#/restaurante">${ic('store')}<span>Sou restaurante</span></a></header>`;}
const empty=(title,desc,button='')=>`<div class="empty">${ic('search')}<h2>${title}</h2><p>${desc}</p>${button}</div>`;
const restaurantCard=r=>`<article class="restaurant"><a class="cover-link" href="#/cardapio/${r.id}"><img src="${esc(r.cover)}" alt="Ambiente do ${esc(r.name)}"><span class="cover-label">${esc(r.cuisine)}</span></a>${heart(r)}<a class="restaurant-title" href="#/cardapio/${r.id}"><h3>${esc(r.name)}</h3>${ic('arrow')}</a><p>${esc(r.description)}</p><span class="muted mini">${ic('clock')}${esc(r.hours)}</span></article>`;
function home(){return `${header()}<main id="main"><section class="welcome"><div class="welcome-copy"><span class="eyebrow">BEM-VINDO AO FOODLINK</span><h1>Olá, cliente!<br><span>O que vai ser hoje?</span></h1><p>Encontre seu próximo sabor.<br>Cardápios, preços e opções, tudo em um só lugar.</p><div class="hero-actions"><a class="btn" href="#/explorar">${ic('search')}Buscar estabelecimento${ic('arrow')}</a><a class="text-link" href="#/escanear">${ic('qr')}Escanear QR Code</a></div><div class="little-note"><span class="line"></span>Simples de escolher. Bom de descobrir.</div></div><a href="#/cardapio/casa-di-pasta" class="welcome-photo"><img src="/assets/carbonara.jpg" alt="Spaghetti alla carbonara com parmesão"><div class="photo-caption"><span>Um clássico que abraça.</span><strong>Casa di Pasta ${ic('arrow')}</strong></div></a></section><section class="section"><div class="section-title"><div><span class="eyebrow">CONHEÇA OS CARDÁPIOS</span><h2>Uma boa escolha começa aqui.</h2></div><a class="text-link" href="#/explorar">Explorar todos ${ic('arrow')}</a></div><div class="restaurant-grid">${db.restaurants.slice(0,3).map(restaurantCard).join('')}</div></section></main>${foot()}`;}
function filteredRestaurants(){return db.restaurants.filter(r=>(category==='Todos'||r.cuisine===category)&&`${r.name} ${r.cuisine}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));}
function directoryResults(){const rs=filteredRestaurants();return rs.length?`${map?`<div class="map" aria-label="Mapa ilustrativo dos locais de demonstração"><span class="map-road road-a"></span><span class="map-road road-b"></span><span class="map-road road-c"></span><span class="park park-a"></span><span class="park park-b"></span><span class="map-place">Vila dos Sabores</span>${rs.map((r,i)=>`<a href="#/cardapio/${r.id}" class="map-pin pin-${i%3}">${ic('pin')}<span>${esc(r.name)}</span></a>`).join('')}<small>Mapa ilustrativo · sem localização em tempo real</small></div>`:''}<div class="restaurant-grid">${rs.map(restaurantCard).join('')}</div>`:empty('Nenhum lugar por aqui','Tente outro nome ou limpe os filtros.',`<button class="btn outline" data-action="clear-search">Limpar busca</button>`);}
function explore(){return `${header('explorar')}<main id="main" class="page"><div class="page-heading"><span class="eyebrow">DESCUBRA NOVOS SABORES</span><h1>Onde vamos comer?</h1><p>Explore os cardápios e escolha com calma.</p></div><div class="search-row"><label class="searchbox">${ic('search')}<input id="restaurant-search" aria-label="Buscar estabelecimento" placeholder="Busque por nome ou tipo de cozinha" value="${esc(search)}"></label><button class="btn outline" data-action="map">${ic(map?'list':'pin')}${map?'Ver lista':'Ver mapa'}</button></div><div class="filters" role="group" aria-label="Tipo de cozinha">${['Todos',...new Set(db.restaurants.map(r=>r.cuisine))].map(c=>`<button class="chip ${c===category?'chosen':''}" data-action="filter" data-value="${esc(c)}">${esc(c)}</button>`).join('')}<span class="demo-note">Locais de demonstração</span></div><div id="results">${directoryResults()}</div></main>${foot()}`;}
function favorites(){const rs=db.restaurants.filter(r=>favorite(r.id));return `${header('favoritos')}<main id="main" class="page"><div class="page-heading"><span class="eyebrow">PARA VOLTAR SEMPRE</span><h1>Seus favoritos!</h1><p>Seus lugares preferidos, sempre por perto.</p></div>${rs.length?`<div class="restaurant-grid">${rs.map(restaurantCard).join('')}</div>`:empty('Sua lista começa com um favorito','Toque no coração de um restaurante para encontrá-lo aqui.',`<a class="btn" href="#/explorar">Explorar cardápios ${ic('arrow')}</a>`)}</main>${foot()}`;}
function scanner(){return `${header('qr')}<main id="main" class="scanner-page"><div><span class="eyebrow">CARDÁPIO DIGITAL</span><h1>Aponte a câmera<br>para o QR Code</h1><p>Acesso rápido ao cardápio do restaurante.</p><div class="scanner"><i></i>${ic('qr')}<span>Leitura de demonstração</span></div><button class="btn wide" data-action="scan">Simular leitura ${ic('arrow')}</button><p class="mini muted">Neste protótipo, a leitura abre o cardápio de exemplo.<br>Você não precisa liberar a câmera.</p><a class="text-link" href="#/explorar">Prefiro buscar um restaurante</a></div></main>${foot()}`;}
const photo=p=>p.photo?`<img src="${esc(p.photo)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="photo-placeholder" aria-label="Produto sem foto">${ic('food')}<span>Sem foto</span></div>`;
const filteredProducts=r=>db.products.filter(p=>p.restaurant===r.id&&(category==='Todos'||p.category===category)&&`${p.name} ${p.description}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
function menuResults(r){const ps=filteredProducts(r);return ps.length?r.categories.map(c=>{const group=ps.filter(p=>p.category===c);return group.length?`<section class="menu-section"><div class="category-heading"><h2>${esc(c)}</h2><span>${group.length} opções</span></div><div class="product-grid">${group.map(p=>`<button class="product ${p.available?'':'unavailable'}" data-action="details" data-id="${p.id}"><div class="product-info"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-bottom"><strong>${price(p.price)}</strong>${!p.available?'<span class="status off">Indisponível</span>':'<span class="more">Ver detalhes '+ic('arrow')+'</span>'}</div></div><div class="product-photo">${photo(p)}</div></button>`).join('')}</div></section>`:''}).join(''):empty('Nenhum prato encontrado','Tente outro termo ou categoria.');}
function menuPage(id){const r=db.restaurants.find(x=>x.id===id);if(!r)return notFound();return `${header()}<main id="main" class="menu-page" style="--restaurant-color:${esc(r.color)}"><section class="menu-cover"><img src="${esc(r.cover)}" alt="${esc(r.name)}"><a class="back-circle" href="#/explorar" aria-label="Voltar aos restaurantes">${ic('back')}</a><div class="menu-cover-copy"><span>${esc(r.cuisine)} · CARDÁPIO DIGITAL</span><h1>${esc(r.name)}</h1><p>${esc(r.description)}</p></div></section><div class="menu-body"><div class="restaurant-meta"><div><span>${ic('clock')}${esc(r.hours)}</span><span>${ic('pin')}${esc(r.address)}</span></div>${heart(r)}</div><div class="menu-tools"><label class="searchbox">${ic('search')}<input id="product-search" aria-label="Buscar no cardápio" placeholder="O que você procura no cardápio?" value="${esc(search)}"></label><div class="filters">${['Todos',...r.categories].map(c=>`<button class="chip ${c===category?'chosen':''}" data-action="filter" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div id="menu-results">${menuResults(r)}</div><p class="demo-disclaimer">Cardápio de demonstração. Consulte o estabelecimento sobre ingredientes e restrições alimentares.</p></div></main>${foot()}`;}
function login(){return `${header()}<main id="main" class="login-page"><section class="login-art"><img src="/assets/casa.jpg" alt="Restaurante acolhedor"><div>${logo()}<h2>Seu cardápio.<br>Sempre do seu jeito.</h2><p>Atualize pratos, preços e disponibilidade<br>em poucos passos.</p></div></section><section class="login-form"><span class="eyebrow">ÁREA DO RESTAURANTE</span><h1>Bom ter você aqui.</h1><p>Entre na demonstração para conhecer o painel e editar o cardápio da Casa di Pasta.</p><button class="btn wide" data-action="enter">Entrar na demonstração ${ic('arrow')}</button><div class="or"><span>ou comece o seu</span></div><button class="btn outline wide" data-action="onboard">Criar meu restaurante ${ic('plus')}</button><p class="demo-disclaimer">Protótipo: os dados ficam salvos neste navegador.<br>Não é necessário criar uma conta ou senha real.</p></section></main>${foot()}`;}
function productRows(r){const ps=db.products.filter(p=>p.restaurant===r.id&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase()));return ps.length?`<div class="table-head"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Disponibilidade</span><span>Ações</span></div>${ps.map(p=>`<div class="table-row"><div class="table-product"><div class="table-photo">${photo(p)}</div><div><strong>${esc(p.name)}</strong><span>${esc(p.description)}</span></div></div><span class="cell-category">${esc(p.category)}</span><strong class="cell-price">${price(p.price)}</strong><button class="switch-wrap" data-action="available" data-id="${p.id}" role="switch" aria-checked="${p.available}" aria-label="Disponibilidade de ${esc(p.name)}"><span class="switch ${p.available?'on':''}"></span><span>${p.available?'Disponível':'Indisponível'}</span></button><div class="row-actions"><button class="icon-btn" data-action="edit-product" data-id="${p.id}" aria-label="Editar ${esc(p.name)}">${ic('edit')}</button><button class="icon-btn danger" data-action="remove-product" data-id="${p.id}" aria-label="Excluir ${esc(p.name)}">${ic('trash')}</button></div></div>`).join('')}`:empty('Seu próximo prato começa aqui',search?'Nenhum produto corresponde à busca.':'Adicione o primeiro produto do cardápio.',`<button class="btn" data-action="add-product">Adicionar produto</button>`);}
function adminContent(r){if(adminSection==='cardapio')return `<div class="workspace-title"><div><span class="eyebrow">${esc(r.name)}</span><h1>Seu cardápio</h1><p>Uma mudança aqui. Um cardápio atualizado para o cliente.</p></div><button class="btn" data-action="add-product">${ic('plus')}Adicionar produto</button></div><div class="admin-toolbar"><label class="searchbox">${ic('search')}<input id="admin-search" aria-label="Buscar produtos" placeholder="Buscar produto ou categoria" value="${esc(search)}"></label><span>${db.products.filter(p=>p.restaurant===r.id).length} produtos</span></div><div id="product-table" class="product-table">${productRows(r)}</div>`;
if(adminSection==='categorias')return `<div class="workspace-title"><div><span class="eyebrow">ORGANIZAÇÃO</span><h1>Categorias</h1><p>Ajude seus clientes a encontrar o que procuram.</p></div><button class="btn" data-action="add-category">${ic('plus')}Nova categoria</button></div><div class="category-list">${r.categories.map((c,i)=>`<div class="category-row"><span class="category-number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(c)}</h3><p>${db.products.filter(p=>p.restaurant===r.id&&p.category===c).length} produtos</p></div><button class="icon-btn" data-action="edit-category" data-value="${esc(c)}" aria-label="Renomear ${esc(c)}">${ic('edit')}</button><button class="icon-btn danger" data-action="remove-category" data-value="${esc(c)}" aria-label="Excluir categoria ${esc(c)}">${ic('trash')}</button></div>`).join('')}</div>`;
if(adminSection==='restaurante')return `<div class="workspace-title"><div><span class="eyebrow">SUA IDENTIDADE</span><h1>Meu restaurante</h1><p>Estas informações aparecem no seu cardápio.</p></div></div><form class="settings-form" data-form="restaurant"><label>Nome do restaurante<input name="name" value="${esc(r.name)}" maxlength="60" required></label><label>Descrição<textarea name="description" rows="3" maxlength="250" required>${esc(r.description)}</textarea></label><div class="form-grid"><label>Tipo de cozinha<input name="cuisine" value="${esc(r.cuisine)}" required maxlength="40"></label><label>Horário de funcionamento<input name="hours" value="${esc(r.hours)}" required maxlength="80"></label></div><label>Localização de exemplo<input name="address" value="${esc(r.address)}" maxlength="100"></label><p class="mini muted">O link do cardápio permanece o mesmo quando você muda o nome.</p><button class="btn" type="submit">${ic('check')}Salvar alterações</button></form>`;
if(adminSection==='aparencia')return `<div class="workspace-title"><div><span class="eyebrow">DO SEU JEITO</span><h1>Aparência</h1><p>Um toque seu, sem complicação.</p></div></div><div class="appearance-grid"><div><h3>Cor de destaque</h3><p class="muted">Escolha a cor das categorias e dos preços.</p><div class="swatches">${[['#B84E29','Terracota'],['#4F7A4E','Verde'],['#2B2B2B','Grafite']].map(([c,n])=>`<button class="swatch ${r.color===c?'chosen':''}" style="--swatch:${c}" data-action="color" data-value="${c}" aria-label="Cor ${n}" aria-pressed="${r.color===c}">${r.color===c?ic('check'):''}</button>`).join('')}</div><h3>Imagem de capa</h3><div class="cover-options">${['casa','verde','brasa'].map(n=>`<button data-action="cover" data-value="/assets/${n}.jpg" class="${r.cover===`/assets/${n}.jpg`?'chosen':''}" aria-label="Capa ${n}"><img src="/assets/${n}.jpg" alt=""></button>`).join('')}</div><a class="btn outline" href="#/cardapio/${r.id}">${ic('eye')}Abrir prévia completa</a></div><div class="mini-preview"><img src="${esc(r.cover)}" alt="Prévia da capa"><div><span class="eyebrow">${esc(r.cuisine)}</span><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><span class="chip chosen" style="background:${r.color};color:white">${esc(r.categories[0]||'Cardápio')}</span></div><small>Prévia do cardápio</small></div></div>`;
return `<div class="workspace-title"><div><span class="eyebrow">SEU CARDÁPIO AO ALCANCE</span><h1>Compartilhar QR Code</h1><p>Um único código. Mesmo quando o cardápio muda.</p></div></div><div class="qr-layout"><div class="qr-paper">${logo()}<h2>${esc(r.name)}</h2><img id="qr-image" alt="QR Code para o cardápio de ${esc(r.name)}"><p>Escaneie e escolha seu próximo sabor.</p><span>Cardápio digital</span></div><div class="qr-instructions"><h2>Pronto para compartilhar.</h2><p>O QR Code aponta para o link abaixo. Preços, produtos e disponibilidade podem mudar sem trocar o código.</p><label>Link do cardápio<input readonly value="${esc(menuUrl(r))}" aria-label="Link do cardápio"></label><div class="qr-actions"><button class="btn" data-action="download-qr">${ic('download')}Baixar QR Code</button><button class="btn outline" data-action="copy-link">${ic('copy')}Copiar link</button></div><a class="text-link" href="#/cardapio/${r.id}">Abrir cardápio ${ic('arrow')}</a><p class="demo-disclaimer">Demonstração local: as edições ficam neste navegador. O acesso de outro aparelho depende de uma publicação online; os dados de exemplo não se sincronizam.</p></div></div>`;}
const adminLinks=[['cardapio','food','Cardápio'],['categorias','list','Categorias'],['aparencia','palette','Aparência'],['restaurante','store','Meu restaurante'],['qr','qr','QR Code']];
function admin(){const r=current();return `<div class="admin-shell"><aside class="sidebar">${logo()}<div class="workspace-label"><img src="${esc(r.cover)}" alt=""><div><strong>${esc(r.name)}</strong><small>Seu espaço</small></div></div><nav aria-label="Painel do restaurante">${adminLinks.map(([id,icon,label])=>`<button class="${id===adminSection?'selected':''}" data-action="admin-section" data-value="${id}">${ic(icon)}${label}${id===adminSection?'<i></i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><a href="#/">${ic('back')}Voltar ao início</a><span>Demonstração</span><p>Dados salvos neste navegador.</p></div></aside><div class="admin-main"><header class="admin-top"><span>Área do restaurante</span><div><a class="text-link" href="#/cardapio/${r.id}">${ic('eye')}Ver cardápio</a><button class="btn outline small" data-action="admin-section" data-value="qr">${ic('qr')}Compartilhar</button></div></header><nav class="mobile-admin-nav" aria-label="Seções do painel">${adminLinks.map(([id,icon,label])=>`<button class="${id===adminSection?'selected':''}" data-action="admin-section" data-value="${id}">${ic(icon)}<span>${label}</span></button>`).join('')}</nav><main id="main" class="workspace">${adminContent(r)}</main><footer class="admin-footer">${ic('check')}Alterações salvas neste navegador <span>FoodLink · Protótipo</span></footer></div></div>`;}
const menuUrl=r=>`${location.href.split('#')[0]}#/cardapio/${r.id}`;
function notFound(){return `${header()}<main id="main" class="page">${empty('Este cardápio não foi encontrado','Volte para explorar os restaurantes de demonstração.',`<a class="btn" href="#/explorar">Explorar restaurantes</a>`)}</main>${foot()}`;}
function render(){const path=route();app.innerHTML=inlineAssets(path==='/'?home():path==='/explorar'?explore():path==='/favoritos'?favorites():path==='/escanear'?scanner():path==='/restaurante'?login():path==='/painel'?admin():path.startsWith('/cardapio/')?menuPage(path.split('/')[2]):notFound());if(path==='/painel'&&adminSection==='qr')QRCode.toDataURL(menuUrl(current()),{width:600,margin:2,color:{dark:'#2B2B2B',light:'#FFFFFF'}}).then(url=>{const el=document.querySelector('#qr-image');if(el)el.src=url;});}
function refreshResults(){const path=route();if(path==='/explorar')document.querySelector('#results').innerHTML=inlineAssets(directoryResults());else if(path.startsWith('/cardapio/')){const r=db.restaurants.find(r=>r.id===path.split('/')[2]);document.querySelector('#menu-results').innerHTML=inlineAssets(menuResults(r));}else if(path==='/painel')document.querySelector('#product-table').innerHTML=inlineAssets(productRows(current()));}
function showModal(content,wide=false){modal.className=wide?'wide-modal':'';modal.innerHTML=inlineAssets(`<button class="icon-btn modal-close" data-action="close" aria-label="Fechar">${ic('close')}</button>${content}`);if(!modal.open)modal.showModal();}
function productForm(id){const r=current(),p=db.products.find(p=>p.id===id)||{name:'',description:'',price:'',category:r.categories[0]||'',photo:'',available:true};if(!r.categories.length){toast('Crie uma categoria antes de adicionar produtos.');adminSection='categorias';render();return;}showModal(`<span class="eyebrow">SEU CARDÁPIO</span><h2>${id?'Editar produto':'Adicionar produto'}</h2><p class="muted">Cada detalhe ajuda na hora de escolher.</p><form data-form="product" data-id="${id||''}"><label>Nome do produto<input name="name" value="${esc(p.name)}" placeholder="Ex.: Bruschetta da casa" required maxlength="70"></label><label>Descrição<textarea name="description" rows="3" required maxlength="350" placeholder="Ingredientes, porção e o que torna seu prato especial">${esc(p.description)}</textarea></label><div class="form-grid"><label>Preço (R$)<input name="price" inputmode="decimal" value="${p.price===''?'':Number(p.price).toFixed(2).replace('.',',')}" placeholder="0,00" required></label><label>Categoria<select name="category">${r.categories.map(c=>`<option ${c===p.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><label>Foto do produto<input name="photo" value="${esc(p.photo)}" placeholder="Cole uma URL https:// de imagem"></label><div class="photo-presets">${['bruschetta','carbonara','arancini','lasanha'].map(x=>`<button type="button" data-action="choose-photo" data-value="/assets/${x}.jpg" aria-label="Usar foto de ${x}"><img src="/assets/${x}.jpg" alt="${x}"></button>`).join('')}</div><label class="check-label"><input name="available" type="checkbox" ${p.available?'checked':''}>Disponível no cardápio</label><p class="form-error" role="alert"></p><div class="form-actions"><button class="btn outline" type="button" data-action="close">Cancelar</button><button class="btn" type="submit">${ic('check')}Salvar produto</button></div></form>`);}
function categoryForm(old=''){showModal(`<span class="eyebrow">ORGANIZAÇÃO</span><h2>${old?'Renomear categoria':'Nova categoria'}</h2><form data-form="category" data-old="${esc(old)}"><label>Nome da categoria<input name="name" value="${esc(old)}" required maxlength="45" placeholder="Ex.: Sobremesas"></label><p class="form-error" role="alert"></p><button class="btn wide" type="submit">Salvar categoria</button></form>`);}
function confirmation(title,desc,action,id,value=''){showModal(`<span class="eyebrow">CONFIRMAR EXCLUSÃO</span><h2>${title}</h2><p>${desc}</p><div class="form-actions"><button class="btn outline" data-action="close">Cancelar</button><button class="btn destructive" data-action="${action}" data-id="${id}" data-value="${esc(value)}">Excluir</button></div>`);}
app.addEventListener('input',e=>{if(['restaurant-search','product-search','admin-search'].includes(e.target.id)){search=e.target.value;refreshResults();}});
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement){e.target.style.opacity='.15';e.target.alt='Imagem não disponível';}},true);
document.addEventListener('click',async e=>{if(e.target.closest('.skip')){e.preventDefault();const main=document.querySelector('#main');main.tabIndex=-1;main.focus();return;}const b=e.target.closest('[data-action]');if(!b)return;const {action,id,value}=b.dataset;const r=current();
if(action==='close')return modal.close();
if(action==='favorite'){db.favorites=favorite(id)?db.favorites.filter(x=>x!==id):[...db.favorites,id];save();render();toast(favorite(id)?'Restaurante salvo nos favoritos.':'Restaurante removido dos favoritos.');}
if(action==='map'){map=!map;render();}
if(action==='filter'){category=value;render();}
if(action==='clear-search'){search='';category='Todos';render();}
if(action==='scan')go('/cardapio/casa-di-pasta');
if(action==='enter'){db.selected='casa-di-pasta';save();adminSection='cardapio';go('/painel');}
if(action==='onboard')showModal(`<span class="eyebrow">SEU PRIMEIRO CARDÁPIO</span><h2>Vamos começar?</h2><p class="muted">Crie um restaurante de demonstração.</p><form data-form="onboard"><label>Nome do restaurante<input name="name" required maxlength="60" placeholder="Como seu restaurante se chama?"></label><label>Tipo de cozinha<input name="cuisine" required maxlength="40" placeholder="Ex.: Brasileira"></label><label>Descrição<textarea name="description" required maxlength="250" placeholder="Conte um pouco sobre o seu restaurante"></textarea></label><p class="form-error" role="alert"></p><button class="btn wide" type="submit">Criar cardápio ${ic('arrow')}</button><p class="mini muted">Nenhuma conta real é criada. Dados salvos neste navegador.</p></form>`);
if(action==='admin-section'){adminSection=value;search='';render();window.scrollTo(0,0);}
if(action==='add-product')productForm();
if(action==='edit-product')productForm(id);
if(action==='choose-photo'){modal.querySelector('[name=photo]').value=value;toast('Foto selecionada.');}
if(action==='available'){const p=db.products.find(p=>p.id===id);p.available=!p.available;save();render();toast(p.available?'Produto disponível no cardápio.':'Produto marcado como indisponível.');}
if(action==='details'){const p=db.products.find(p=>p.id===id);showModal(`<div class="detail-image">${photo(p)}</div><div class="detail-text"><span class="eyebrow">${esc(p.category)}</span><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="detail-price"><strong>${price(p.price)}</strong><span class="status ${p.available?'':'off'}">${p.available?'Disponível':'Indisponível no momento'}</span></div><p class="mini muted">Informações demonstrativas. Confirme ingredientes com o restaurante.</p></div>`,true);}
if(action==='remove-product'){const p=db.products.find(p=>p.id===id);confirmation('Excluir este produto?',`<strong>${esc(p.name)}</strong> será removido do seu cardápio de demonstração.`,'confirm-product',id);}
if(action==='confirm-product'){db.products=db.products.filter(p=>p.id!==id);save();modal.close();render();toast('Produto excluído.');}
if(action==='add-category')categoryForm();
if(action==='edit-category')categoryForm(value);
if(action==='remove-category'){if(db.products.some(p=>p.restaurant===r.id&&p.category===value))toast('Mova ou exclua os produtos desta categoria antes de removê-la.');else confirmation('Excluir esta categoria?',`A categoria <strong>${esc(value)}</strong> está vazia e será removida.`,'confirm-category','',value);}
if(action==='confirm-category'){r.categories=r.categories.filter(c=>c!==value);save();modal.close();render();toast('Categoria excluída.');}
if(action==='color'){r.color=value;save();render();toast('Cor atualizada.');}
if(action==='cover'){r.cover=value;save();render();toast('Capa atualizada.');}
if(action==='copy-link'){try{await navigator.clipboard.writeText(menuUrl(r));toast('Link copiado!');}catch{toast('Selecione e copie o link exibido acima.');}}
if(action==='download-qr'){const a=document.createElement('a');a.href=await QRCode.toDataURL(menuUrl(r),{width:1200,margin:3});a.download=`foodlink-${r.id}-qr.png`;a.click();toast('QR Code preparado para download.');}
});
document.addEventListener('submit',e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const f=new FormData(form),get=name=>String(f.get(name)||'').trim(),r=current();const fail=message=>{const field=form.querySelector('.form-error');if(field)field.textContent=message;else toast(message);};
if(form.dataset.form==='product'){const raw=get('price'),normalized=raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw,n=Number(normalized);if(!get('name')||!get('description'))return fail('Preencha o nome e a descrição do produto.');if(!Number.isFinite(n)||n<=0)return fail('Informe um preço maior que zero, como 24,90.');const image=get('photo');if(image&&!/^https:\/\//.test(image)&&!/^\/assets\/[a-z-]+\.(jpg|png)$/.test(image))return fail('Use uma URL https:// válida ou escolha uma das fotos abaixo.');const p={id:form.dataset.id||crypto.randomUUID(),restaurant:r.id,name:get('name'),description:get('description'),price:n,category:get('category'),photo:image,available:f.has('available')};const idx=db.products.findIndex(x=>x.id===p.id);if(idx<0)db.products.push(p);else db.products[idx]=p;if(save()){modal.close();render();toast('Produto salvo no cardápio.');}}
if(form.dataset.form==='category'){const name=get('name'),old=form.dataset.old;if(!name)return fail('Informe um nome para a categoria.');if(r.categories.some(c=>c!==old&&c.toLowerCase()===name.toLowerCase()))return fail('Já existe uma categoria com esse nome.');if(old){r.categories=r.categories.map(c=>c===old?name:c);db.products.forEach(p=>{if(p.restaurant===r.id&&p.category===old)p.category=name;});}else r.categories.push(name);save();modal.close();render();toast('Categoria salva.');}
if(form.dataset.form==='restaurant'){if(!get('name')||!get('description')||!get('cuisine'))return fail('Preencha os campos obrigatórios.');Object.assign(r,{name:get('name'),description:get('description'),cuisine:get('cuisine'),hours:get('hours'),address:get('address')});save();render();toast('Informações do restaurante atualizadas.');}
if(form.dataset.form==='onboard'){const name=get('name');if(!name||!get('cuisine')||!get('description'))return fail('Preencha todos os campos.');const slug=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'restaurante';const id=db.restaurants.some(r=>r.id===slug)?`${slug}-${Date.now().toString(36)}`:slug;db.restaurants.push({id,name,cuisine:get('cuisine'),description:get('description'),cover:'/assets/casa.jpg',hours:'Seg a sáb · 11h às 22h',address:'Local de demonstração',color:'#B84E29',categories:['Entradas','Pratos principais','Bebidas','Sobremesas']});db.selected=id;save();modal.close();adminSection='cardapio';go('/painel');toast('Seu restaurante foi criado. Adicione o primeiro produto.');}
});
window.addEventListener('hashchange',()=>{search='';category='Todos';modal.close();render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{db=JSON.parse(e.newValue);render();}catch{}}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
render();
